using System.IO;
using OutlookAI.TaskPane.Chat;
using Xunit;

namespace OutlookAI.Tests.TaskPane.Chat
{
    public class WebView2BootstrapTests
    {
        // Resource names use "." as both folder separator and extension
        // boundary. The helper has to disambiguate: last dot = extension,
        // earlier dots = folder separators, and ".min.js" is treated as a
        // single suffix on the filename (not a fake folder).

        [Fact]
        public void ResourceNameToRelativePath_SimpleFile()
        {
            var result = WebView2Bootstrap.ResourceNameToRelativePath("index.html");
            Assert.Equal("index.html", result);
        }

        [Fact]
        public void ResourceNameToRelativePath_SingleFolderPrefix()
        {
            var result = WebView2Bootstrap.ResourceNameToRelativePath("vendor.marked.js");
            Assert.Equal(Path.Combine("vendor", "marked.js"), result);
        }

        [Fact]
        public void ResourceNameToRelativePath_MinifiedFile_KeepsMinOnFilename()
        {
            // "vendor.marked.min.js" must become vendor\marked.min.js, NOT
            // vendor\marked\min.js.
            var result = WebView2Bootstrap.ResourceNameToRelativePath("vendor.marked.min.js");
            Assert.Equal(Path.Combine("vendor", "marked.min.js"), result);
        }

        [Fact]
        public void ResourceNameToRelativePath_NestedFolder()
        {
            var result = WebView2Bootstrap.ResourceNameToRelativePath("vendor.highlight.styles.github.css");
            Assert.Equal(
                Path.Combine("vendor", "highlight", "styles", "github.css"),
                result);
        }

        [Fact]
        public void ResourceNameToRelativePath_NoExtension_ReturnsUnchanged()
        {
            // Unusual case: no dot at all.
            var result = WebView2Bootstrap.ResourceNameToRelativePath("README");
            Assert.Equal("README", result);
        }

        [Theory]
        [InlineData("print-template.html", "print-template.html")]
        [InlineData("print-styles.css", "print-styles.css")]
        public void ResourceNameToRelativePath_HyphenatedPrintResources(string resourceTail, string expectedPath)
        {
            var result = WebView2Bootstrap.ResourceNameToRelativePath(resourceTail);
            Assert.Equal(expectedPath, result);
        }

        [Fact]
        public void VirtualHost_IsExpectedValue()
        {
            // The virtual host name is part of the public contract - the
            // chat HTML/JS will resolve resources via this URL.
            Assert.Equal("outlookai.local", WebView2Bootstrap.VirtualHost);
        }

        [Fact]
        public void WebUi_LoadsSharedMarkdownBeforeChat()
        {
            var indexHtml = File.ReadAllText(FindSourceFile("OutlookAI", "WebUI", "index.html"));

            var markdownIndex = indexHtml.IndexOf("<script src=\"markdown.js\"></script>");
            var chatIndex = indexHtml.IndexOf("<script src=\"chat.js\"></script>");

            Assert.True(markdownIndex >= 0, "index.html should load markdown.js.");
            Assert.True(chatIndex >= 0, "index.html should load chat.js.");
            Assert.True(markdownIndex < chatIndex, "markdown.js should load before chat.js.");
        }

        [Fact]
        public void Project_EmbedsSharedMarkdownResource()
        {
            var projectXml = File.ReadAllText(FindSourceFile("OutlookAI", "OutlookAI.csproj"));

            Assert.Contains("<EmbeddedResource Include=\"WebUI\\markdown.js\">", projectXml);
            Assert.Contains("<LogicalName>OutlookAI.WebUI.markdown.js</LogicalName>", projectXml);
        }

        [Fact]
        public void Project_EmbedsPrintTemplateResources()
        {
            var projectXml = File.ReadAllText(FindSourceFile("OutlookAI", "OutlookAI.csproj"));

            Assert.Contains("<EmbeddedResource Include=\"WebUI\\print-template.html\">", projectXml);
            Assert.Contains("<LogicalName>OutlookAI.WebUI.print-template.html</LogicalName>", projectXml);
            Assert.Contains("<EmbeddedResource Include=\"WebUI\\print-styles.css\">", projectXml);
            Assert.Contains("<LogicalName>OutlookAI.WebUI.print-styles.css</LogicalName>", projectXml);
        }

        [Fact]
        public void PrintTemplate_ReferencesStylesMarkdownAndRendererTokens()
        {
            var templateHtml = File.ReadAllText(FindSourceFile("OutlookAI", "WebUI", "print-template.html"));

            Assert.Contains("<link rel=\"stylesheet\" href=\"print-styles.css\">", templateHtml);
            Assert.Contains("<script src=\"markdown.js\"></script>", templateHtml);
            Assert.Contains("<title>__TITLE_TEXT__</title>", templateHtml);
            Assert.Contains("<h1 class=\"doc-title\">__TITLE_TEXT__</h1>", templateHtml);
            Assert.Contains("<p class=\"doc-subtitle\">__SUBTITLE_TEXT__</p>", templateHtml);
            Assert.Contains("Generated by OutlookAI &middot; __GENERATED_AT__", templateHtml);
            Assert.Contains("__MD_INJECT__", templateHtml);
            Assert.Contains("window.markdown.render(window.__OUTLOOKAI_MD__ || '')", templateHtml);
            Assert.Contains("data-render-state=\"loading\"", templateHtml);
            Assert.Contains("data-render-state", templateHtml);
            Assert.Contains("ready", templateHtml);
            Assert.Contains("error", templateHtml);
        }

        [Fact]
        public void WebUi_ChatRendersFileSavedToolResultsAsFileCard()
        {
            var chatJs = File.ReadAllText(FindSourceFile("OutlookAI", "WebUI", "chat.js"));
            var stylesCss = File.ReadAllText(FindSourceFile("OutlookAI", "WebUI", "styles.css"));

            Assert.Contains("appendFileCardToMessage", chatJs);
            Assert.Contains("onFileSaved", chatJs);
            Assert.Contains("onExportError", chatJs);
            Assert.Contains("Export action failed.", chatJs);
            Assert.Contains("result_type === 'file_saved'", chatJs);
            Assert.Contains("open_file", chatJs);
            Assert.Contains("reveal_in_explorer", chatJs);
            Assert.DoesNotContain("renderInlineErrorCard", chatJs);

            Assert.Contains(".msg-attachments", stylesCss);
            Assert.Contains(".file-card", stylesCss);
            Assert.Contains(".file-card-btn", stylesCss);
        }

        [Fact]
        public void WebUi_ChatSupportsPerMessagePdfExport()
        {
            var chatJs = File.ReadAllText(FindSourceFile("OutlookAI", "WebUI", "chat.js"));
            var stylesCss = File.ReadAllText(FindSourceFile("OutlookAI", "WebUI", "styles.css"));

            Assert.Contains("handleExportPdf", chatJs);
            Assert.Contains("deriveFilenameHint", chatJs);
            Assert.Contains("export_pdf", chatJs);
            Assert.Contains("content_markdown", chatJs);
            Assert.Contains("filename_hint", chatJs);
            Assert.Contains("Save message as PDF", chatJs);
            Assert.Contains("entry.raw", chatJs);
            Assert.Contains("setExportButtonPending", chatJs);
            Assert.Contains("resetExportButton", chatJs);
            Assert.Contains("onFileSaved", chatJs);
            Assert.Contains("onExportError", chatJs);
            Assert.Contains("heading.replace(/\\s+#+\\s*$/, '')", chatJs);
            Assert.DoesNotContain("^#{1,3}\\s+(.+?)\\s*#*\\s*$", chatJs);

            Assert.Contains(".msg-action-pdf", stylesCss);
            Assert.Contains(".msg-assistant:hover .msg-action", stylesCss);
            Assert.Contains(".msg-assistant.is-streaming .msg-action", stylesCss);
            Assert.Contains(".msg-action:disabled", stylesCss);
        }

        private static string FindSourceFile(params string[] relativeParts)
        {
            var current = new DirectoryInfo(Directory.GetCurrentDirectory());
            while (current != null)
            {
                var candidate = Path.Combine(current.FullName, Path.Combine(relativeParts));
                if (File.Exists(candidate)) return candidate;

                current = current.Parent;
            }

            throw new FileNotFoundException("Could not find source file.", Path.Combine(relativeParts));
        }
    }
}
